CREATE TABLE `alerts` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`author` BIGINT(20) UNSIGNED NOT NULL,
	`channel_type` ENUM('dm','group','text') NOT NULL,
	`channel` BIGINT(20) UNSIGNED NOT NULL,
	`names` VARCHAR(256) NULL DEFAULT NULL,
	`servers` VARCHAR(32) NULL DEFAULT NULL,
	`deleted` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
